version: '3'
services:
  webapp:
    build: .
    container_name: "vue-container"
    image: muhohoweb/vue-app:nginx
    ports:
      - "3000:80"
    environment:
      - APP_VERSION=1.0.8
      - API_URL=http://localhost:9000/api
      - API_KEY=eyd78sd98ds7d7s9sd999909ds
